import type { BlogSeriesTrack } from "@/lib/blogSeries";

export type AiMlSeriesTrack = BlogSeriesTrack & {
  overview: string;
  highlights: string[];
  focusAreas: string[];
  starterTopics: string[];
};

const AI_ML_SERIES_BASE: AiMlSeriesTrack[] = [
  {
    slug: "mathematics-mastery",
    title: "Mathematics Mastery",
    detailTitle: "Mathematics Mastery",
    subtitle: "Linear algebra, calculus, optimization, and the mathematical intuition behind modern machine learning.",
    tags: ["Mathematics", "Foundations", "AI/ML"],
    keywords: ["mathematics", "linear algebra", "calculus", "optimization", "machine learning math"],
    logos: ["/brand-logos/stacks/python.svg", "/brand-logos/stacks/scikitlearn.svg"],
    rgb: "14 165 233",
    overview: "This track builds the math intuition behind vectors, matrices, gradients, probability, and optimization so AI and ML concepts stop feeling like memorized formulas.",
    highlights: ["Vectors to tensors", "Derivatives and gradients", "Optimization intuition", "Math for ML interviews"],
    focusAreas: ["Linear algebra", "Calculus", "Probability basics", "Optimization foundations"],
    starterTopics: ["Vectors and matrices", "Matrix multiplication", "Derivatives and chain rule", "Gradient descent", "Probability distributions", "Eigenvalues and SVD"],
  },
  {
    slug: "statistics-mastery",
    title: "Statistics Mastery",
    detailTitle: "Statistics Mastery",
    subtitle: "Descriptive stats, inference, distributions, experimentation, and statistical thinking for data science.",
    tags: ["Statistics", "Inference", "AI/ML"],
    keywords: ["statistics", "probability", "hypothesis testing", "confidence intervals", "a/b testing"],
    logos: ["/brand-logos/stacks/python.svg", "/brand-logos/stacks/scikitlearn.svg"],
    rgb: "16 185 129",
    overview: "This track covers the statistics you actually use in ML and analytics: distributions, sampling, significance, bias, variance, and experiment interpretation.",
    highlights: ["Probability and distributions", "Confidence intervals", "Hypothesis testing", "A/B testing"],
    focusAreas: ["Descriptive statistics", "Inferential statistics", "Experimentation", "Statistical pitfalls"],
    starterTopics: ["Mean, median, variance", "Normal and binomial distributions", "Sampling theory", "P-values", "Confidence intervals", "Type I and Type II errors"],
  },
  {
    slug: "python-mastery",
    title: "Python Mastery",
    detailTitle: "Python Mastery",
    subtitle: "Python fundamentals, data structures, typing, notebooks, packaging, and AI-focused coding patterns.",
    tags: ["Python", "Programming", "AI/ML"],
    keywords: ["python", "python programming", "typing", "notebooks", "packages", "ml python"],
    logos: ["/brand-logos/stacks/python.svg"],
    rgb: "234 179 8",
    overview: "This track focuses on writing clean Python for data, automation, and ML work, with emphasis on notebooks, packages, environments, and production-friendly patterns.",
    highlights: ["Core syntax", "Data structures", "Typing and packaging", "Python for ML workflows"],
    focusAreas: ["Python basics", "Functions and classes", "Typing and modules", "Environment management"],
    starterTopics: ["Lists, dicts, sets", "Functions and decorators", "Classes and dataclasses", "Virtual environments", "Jupyter workflows", "Typing and linting"],
  },
  {
    slug: "numpy-mastery",
    title: "NumPy Mastery",
    detailTitle: "NumPy Mastery",
    subtitle: "Arrays, broadcasting, vectorization, shapes, memory layout, and fast numerical computing.",
    tags: ["NumPy", "Arrays", "AI/ML"],
    keywords: ["numpy", "arrays", "broadcasting", "vectorization", "ndarray", "numerical computing"],
    logos: ["/brand-logos/stacks/python.svg"],
    rgb: "59 130 246",
    overview: "This track teaches how NumPy arrays work under the hood so you can reason about shapes, broadcasting, performance, and the numerical foundations of ML code.",
    highlights: ["ndarray fundamentals", "Broadcasting", "Vectorized computing", "Numerical performance"],
    focusAreas: ["Array creation and slicing", "Broadcasting rules", "Linear algebra helpers", "Memory-aware operations"],
    starterTopics: ["ndarray basics", "Reshape and transpose", "Broadcasting mental model", "Vectorization vs loops", "Axis operations", "Random number utilities"],
  },
  {
    slug: "pandas-mastery",
    title: "Pandas Mastery",
    detailTitle: "Pandas Mastery",
    subtitle: "DataFrames, cleaning, joins, grouping, time series, and reliable analytical data preparation.",
    tags: ["Pandas", "DataFrames", "AI/ML"],
    keywords: ["pandas", "dataframe", "data cleaning", "groupby", "joins", "time series"],
    logos: ["/brand-logos/stacks/python.svg", "/brand-logos/stacks/postgresql.svg"],
    rgb: "139 92 246",
    overview: "This track focuses on real-world Pandas workflows: ingesting messy data, cleaning it, reshaping it, and preparing trustworthy datasets for downstream analytics or models.",
    highlights: ["Data cleaning", "Joins and groupby", "Time series prep", "Data quality checks"],
    focusAreas: ["DataFrame operations", "Missing values", "Aggregation", "Reshaping"],
    starterTopics: ["Read and inspect data", "Filtering and indexing", "GroupBy and aggregation", "Merge and join", "Pivot and melt", "DateTime handling"],
  },
  {
    slug: "matplotlib-mastery",
    title: "Matplotlib Mastery",
    detailTitle: "Matplotlib Mastery",
    subtitle: "Plotting primitives, figure design, annotations, dashboards, and visual storytelling for technical work.",
    tags: ["Matplotlib", "Visualization", "AI/ML"],
    keywords: ["matplotlib", "plots", "visualization", "charting", "technical visualization"],
    logos: ["/brand-logos/stacks/python.svg"],
    rgb: "249 115 22",
    overview: "This track is about building clear, publication-ready plots instead of default charts, with control over layout, labels, scales, and multi-panel figure design.",
    highlights: ["Figure fundamentals", "Custom styling", "Annotations and layout", "Technical storytelling"],
    focusAreas: ["Line and scatter plots", "Axes and subplots", "Styling and themes", "Multi-panel figures"],
    starterTopics: ["Figure and axes", "Line, bar, histogram", "Legends and labels", "Subplots and gridspec", "Annotations", "Saving high-quality figures"],
  },
  {
    slug: "seaborn-mastery",
    title: "Seaborn Mastery",
    detailTitle: "Seaborn Mastery",
    subtitle: "Statistical visualization, distribution plots, relational charts, categorical analysis, and EDA visuals.",
    tags: ["Seaborn", "EDA", "AI/ML"],
    keywords: ["seaborn", "eda", "statistical visualization", "distributions", "correlation"],
    logos: ["/brand-logos/stacks/python.svg", "/brand-logos/stacks/scikitlearn.svg"],
    rgb: "236 72 153",
    overview: "This track focuses on Seaborn as the fastest way to produce statistically meaningful charts during analysis, feature exploration, and model diagnostics.",
    highlights: ["Distributions and KDE", "Categorical charts", "Pair plots and heatmaps", "EDA workflows"],
    focusAreas: ["Relational plots", "Categorical plots", "Distribution plots", "Statistical summaries"],
    starterTopics: ["Scatterplot and lineplot", "Boxplot and violinplot", "Histplot and kdeplot", "Heatmaps", "Pairplot", "Facet grids"],
  },
  {
    slug: "feature-engineering-mastery",
    title: "Feature Engineering Mastery",
    detailTitle: "Feature Engineering Mastery",
    subtitle: "Encoding, scaling, transformation, leakage prevention, and building stable model-ready features.",
    tags: ["Features", "Data Prep", "AI/ML"],
    keywords: ["feature engineering", "encoding", "scaling", "feature leakage", "transformation", "ml features"],
    logos: ["/brand-logos/stacks/scikitlearn.svg", "/brand-logos/stacks/python.svg"],
    rgb: "34 197 94",
    overview: "This track shows how raw columns become useful model signals, and how to avoid leakage, instability, and brittle preprocessing in production pipelines.",
    highlights: ["Scaling and encoding", "Leakage prevention", "Feature selection", "Pipeline-ready transforms"],
    focusAreas: ["Categorical encoding", "Numerical transformation", "Feature selection", "Production-safe preprocessing"],
    starterTopics: ["Standardization vs normalization", "One-hot and target encoding", "Handling missing data", "Date/time features", "Leakage detection", "Sklearn pipelines"],
  },
  {
    slug: "machine-learning-core-mastery",
    title: "Machine Learning Core Mastery",
    detailTitle: "Machine Learning Core Mastery",
    subtitle: "A structured foundation across supervised, unsupervised, and reinforcement learning.",
    tags: ["Machine Learning", "Core", "AI/ML"],
    keywords: ["machine learning core", "supervised learning", "unsupervised learning", "reinforcement learning"],
    logos: ["/brand-logos/stacks/scikitlearn.svg", "/brand-logos/stacks/python.svg"],
    rgb: "6 182 212",
    href: "/ai-ml-blogs/machine-learning-core-mastery",
    actionLabel: "Open ML Core Paths",
    overview: "This track is the main machine learning decision map. It separates the field into supervised, unsupervised, and reinforcement learning so the learner can understand where each class of problems belongs.",
    highlights: ["Supervised learning path", "Unsupervised learning path", "Reinforcement learning path", "Branch-first learning map"],
    focusAreas: ["Prediction problems", "Pattern discovery", "Sequential decision making", "Evaluation basics"],
    starterTopics: ["Regression and classification", "Clustering and dimensionality reduction", "Rewards and policies", "Model evaluation", "Bias and variance", "Practical ML workflows"],
  },
  {
    slug: "deep-learning-core-mastery",
    title: "Deep Learning Core Mastery",
    detailTitle: "Deep Learning Core Mastery",
    subtitle: "Neural networks, training loops, backpropagation, optimization, and deep learning systems thinking.",
    tags: ["Deep Learning", "Neural Nets", "AI/ML"],
    keywords: ["deep learning", "neural networks", "backpropagation", "optimization", "pytorch", "tensorflow"],
    logos: ["/brand-logos/stacks/pytorch.svg", "/brand-logos/stacks/tensorflow.svg"],
    rgb: "124 58 237",
    overview: "This track starts from perceptrons and backpropagation, then moves toward modern training loops, model design, regularization, and deployment-aware deep learning.",
    highlights: ["Neural network basics", "Backpropagation", "Training stability", "Framework patterns"],
    focusAreas: ["Neural network fundamentals", "Optimization", "Architectures", "Training diagnostics"],
    starterTopics: ["Perceptrons and activations", "Backpropagation", "Loss functions", "Optimizers", "CNN and RNN basics", "Regularization"],
  },
  {
    slug: "nlp-mastery",
    title: "NLP Mastery",
    detailTitle: "NLP Mastery",
    subtitle: "Tokenization, embeddings, transformers, retrieval, evaluation, and modern language system design.",
    tags: ["NLP", "Language", "AI/ML"],
    keywords: ["nlp", "transformers", "tokenization", "embeddings", "language models", "rag"],
    logos: ["/brand-logos/stacks/huggingface.svg", "/brand-logos/stacks/python.svg"],
    rgb: "217 70 239",
    overview: "This track covers the progression from classic NLP preprocessing to embeddings, transformers, retrieval pipelines, evaluation, and modern applied language systems.",
    highlights: ["Text preprocessing", "Embeddings", "Transformers", "RAG and evaluation"],
    focusAreas: ["Text representation", "Sequence models", "Transformer stack", "Applied NLP systems"],
    starterTopics: ["Tokenization", "Bag of words and TF-IDF", "Word embeddings", "Attention and transformers", "Prompting and retrieval", "NLP evaluation"],
  },
  {
    slug: "computer-vision-mastery",
    title: "Computer Vision Mastery",
    detailTitle: "Computer Vision Mastery",
    subtitle: "Image fundamentals, CNNs, detection, segmentation, embeddings, and production vision pipelines.",
    tags: ["Computer Vision", "Vision AI", "AI/ML"],
    keywords: ["computer vision", "cnn", "object detection", "segmentation", "image embeddings"],
    logos: ["/brand-logos/stacks/pytorch.svg", "/brand-logos/stacks/python.svg"],
    rgb: "244 63 94",
    overview: "This track teaches how images become tensors, how vision models learn patterns, and how detection, segmentation, and embeddings are applied in production systems.",
    highlights: ["Image fundamentals", "CNN pipelines", "Detection and segmentation", "Vision deployments"],
    focusAreas: ["Image preprocessing", "CNN architectures", "Detection and segmentation", "Real-world CV systems"],
    starterTopics: ["Pixels and channels", "Convolutions and pooling", "Classification pipelines", "Object detection", "Segmentation", "Vision embeddings"],
  },
];

export const AI_ML_SERIES: AiMlSeriesTrack[] = AI_ML_SERIES_BASE.map((series) => ({
  ...series,
  href: series.href || `/ai-ml-blogs/${series.slug}`,
}));

export const AI_ML_SERIES_BY_SLUG = new Map(AI_ML_SERIES.map((series) => [series.slug, series]));

export const getAiMlSeriesHref = (series: AiMlSeriesTrack) => series.href || `/ai-ml-blogs/${series.slug}`;
