-- LLM Galaxy: add metadata fields + seed curated families (verified Feb 2026).

alter table public.llm_models
  add column if not exists homepage_url text,
  add column if not exists huggingface_url text,
  add column if not exists license text,
  add column if not exists considerations text[];

-- Curated "family" rows: one row per model family. Keep `versions` as JSON array for the family timeline.
insert into public.llm_models (
  slug,
  name,
  company,
  description,
  logo,
  color,
  parameters,
  context_window,
  pricing,
  speed,
  architecture,
  is_open_source,
  is_multimodal,
  benchmarks,
  strengths,
  weaknesses,
  use_cases,
  considerations,
  api_docs_url,
  homepage_url,
  huggingface_url,
  license,
  versions,
  is_trending,
  release_date
)
values
(
  'gpt',
  'GPT',
  'OpenAI',
  'OpenAI''s GPT family: general-purpose frontier models optimized for reasoning, coding, tool-use, and production agents.',
  '🤖',
  'from-emerald-500 to-teal-600',
  null,
  null,
  'API',
  'Fast',
  'Transformer',
  false,
  true,
  null,
  array['Strong general reasoning', 'Coding and refactoring', 'Tool use and agents', 'Multimodal understanding'],
  array['Closed-source', 'Costs and rate limits', 'Policy/safety constraints vary by tier'],
  array['Reasoning','Coding','Agents','Chatbots','Multimodal','Enterprise','RAG'],
  array['Prefer Azure OpenAI for enterprise governance', 'Budget for token costs and retries', 'Use evals for safety and regressions'],
  'https://platform.openai.com/docs',
  'https://openai.com',
  null,
  'Proprietary',
  '[
    {"name":"GPT-5.3-Codex","highlight":"Coding-focused generation"},
    {"name":"GPT-5.2","highlight":"Latest general flagship"},
    {"name":"GPT-4o","highlight":"Multimodal, fast"}
  ]'::jsonb,
  true,
  'Feb 2026'
),
(
  'claude',
  'Claude',
  'Anthropic',
  'Anthropic''s Claude family: long-context assistants designed for strong analysis, safety, and high-quality writing and coding.',
  '🧠',
  'from-orange-500 to-amber-600',
  null,
  null,
  'API',
  'Fast',
  'Transformer',
  false,
  true,
  null,
  array['Long-context analysis', 'High-quality writing', 'Reliable instruction following', 'Strong coding assistance'],
  array['Closed-source', 'Tool-use behavior depends on product tier', 'Regional availability varies'],
  array['Long context','Analysis','Safety','Coding','Chatbots','Enterprise','RAG','Multimodal'],
  array['Treat as closed-source: plan for vendor risk', 'Use red-teaming for safety-critical workflows', 'Prefer structured tool contracts for agents'],
  'https://docs.anthropic.com',
  'https://www.anthropic.com',
  null,
  'Proprietary',
  '[
    {"name":"Claude Opus 4.6","highlight":"Flagship reasoning & writing"},
    {"name":"Claude Sonnet 4","highlight":"Balanced performance"},
    {"name":"Claude Haiku 3.5","highlight":"Fast + cost-efficient"}
  ]'::jsonb,
  true,
  'Feb 2026'
),
(
  'gemini',
  'Gemini',
  'Google',
  'Google''s Gemini family: native multimodal models integrated with Google''s ecosystem for research, assistants, and tool-use.',
  '✨',
  'from-blue-500 to-indigo-600',
  null,
  null,
  'API',
  'Medium',
  'Multimodal Transformer',
  false,
  true,
  null,
  array['Multimodal reasoning', 'Research and summarization', 'Large context workflows', 'Google ecosystem integration'],
  array['Closed-source', 'Capability varies by region/product', 'Pricing and quotas vary'],
  array['Multimodal','Research','Scale','Agents','RAG','Chatbots','Enterprise'],
  array['Validate regional availability early', 'Use robust retrieval for factual apps', 'Track quota behavior under load'],
  'https://ai.google.dev/gemini-api/docs',
  'https://deepmind.google/technologies/gemini/',
  null,
  'Proprietary',
  '[
    {"name":"Gemini 3","highlight":"Next-gen multimodal"},
    {"name":"Gemini 2","highlight":"Agentic workflows"},
    {"name":"Gemini 1.5","highlight":"Long-context"}
  ]'::jsonb,
  true,
  'Feb 2026'
),
(
  'llama',
  'Llama',
  'Meta',
  'Meta''s Llama family: open-weight models designed for self-hosting, fine-tuning, and building private AI systems.',
  '🦙',
  'from-violet-500 to-purple-600',
  null,
  null,
  'Free',
  'Medium',
  'Transformer',
  true,
  true,
  null,
  array['Self-hosted deployments', 'Fine-tuning', 'Private RAG', 'Cost control'],
  array['Requires infra/ops to host', 'Licensing constraints vary by use', 'Quality depends on tuning and data'],
  array['Open source','Fine-tuning','Enterprise','RAG','Agents','Chatbots'],
  array['Review license for your distribution model', 'Plan for GPU/latency budgets', 'Add evals and guardrails for production'],
  'https://ai.meta.com/llama/',
  'https://ai.meta.com/llama/',
  'https://huggingface.co/meta-llama',
  'Meta Llama License',
  '[
    {"name":"Llama 4 Scout","highlight":"Efficient open-weight" ,"hf_url":"https://huggingface.co/meta-llama"},
    {"name":"Llama 4 Maverick","highlight":"Frontier open-weight","hf_url":"https://huggingface.co/meta-llama"},
    {"name":"Llama 4 Behemoth (preview)","highlight":"Preview frontier","hf_url":"https://huggingface.co/meta-llama"}
  ]'::jsonb,
  true,
  'Feb 2026'
),
(
  'qwen',
  'Qwen',
  'Alibaba',
  'Alibaba''s Qwen family: open-weight multilingual models with strong math and coding variants.',
  '🌐',
  'from-red-500 to-pink-600',
  null,
  null,
  'Free',
  'Fast',
  'Transformer (incl. MoE variants)',
  true,
  true,
  null,
  array['Multilingual support', 'Strong coding variants', 'Math and reasoning', 'Self-hosted RAG'],
  array['Self-hosting complexity', 'Docs quality varies by model', 'Benchmark drift across forks'],
  array['Multilingual','Coding','Math','Open source','RAG','Agents'],
  array['Prefer official repos for security', 'Pin versions in production', 'Validate safety alignment for your domain'],
  'https://huggingface.co/Qwen',
  'https://huggingface.co/Qwen',
  'https://huggingface.co/Qwen',
  'Apache-2.0 / Qwen License (varies)',
  '[
    {"name":"Qwen3","highlight":"Next-gen open-weight","hf_url":"https://huggingface.co/Qwen"},
    {"name":"Qwen2.5","highlight":"Strong coding + multilingual","hf_url":"https://huggingface.co/Qwen"}
  ]'::jsonb,
  true,
  'Feb 2026'
),
(
  'deepseek',
  'DeepSeek',
  'DeepSeek',
  'DeepSeek family: cost-efficient models with strong coding and reasoning variants; some releases have open weights.',
  '🔍',
  'from-fuchsia-500 to-pink-600',
  null,
  null,
  'Free / API',
  'Fast',
  'Transformer (incl. MoE variants)',
  true,
  false,
  null,
  array['Coding performance', 'Cost-effective deployment', 'Competitive open-weight variants'],
  array['English ecosystem smaller', 'Self-hosting required for open weights', 'Evaluate safety for your use case'],
  array['Coding','Reasoning','Open source','RAG','Agents'],
  array['Prefer official org repos', 'Validate training data constraints', 'Run regression evals on upgrades'],
  'https://huggingface.co/deepseek-ai',
  'https://www.deepseek.com',
  'https://huggingface.co/deepseek-ai',
  'DeepSeek license (varies)',
  '[
    {"name":"DeepSeek V3","highlight":"Frontier open-weight","hf_url":"https://huggingface.co/deepseek-ai"},
    {"name":"DeepSeek Coder","highlight":"Coding specialist","hf_url":"https://huggingface.co/deepseek-ai"}
  ]'::jsonb,
  true,
  'Feb 2026'
),
(
  'mistral',
  'Mistral',
  'Mistral AI',
  'Mistral family: efficient open-weight and commercial models; known for strong performance-per-cost and MoE architectures.',
  '💨',
  'from-cyan-500 to-sky-600',
  null,
  null,
  'Free / API',
  'Fast',
  'Transformer / MoE',
  true,
  true,
  null,
  array['Efficient inference', 'Open-weight variants', 'Strong for production engineering'],
  array['Multimodal coverage varies', 'Model lineup moves quickly', 'Requires infra for self-hosting'],
  array['Efficiency','Open source','Coding','Enterprise','RAG','Multimodal'],
  array['Pick a stable tag for production', 'Use quantization carefully', 'Check EU data residency needs'],
  'https://docs.mistral.ai',
  'https://mistral.ai',
  'https://huggingface.co/mistralai',
  'Apache-2.0 / Mistral license (varies)',
  '[
    {"name":"Pixtral 12B","highlight":"Multimodal open-weight","hf_url":"https://huggingface.co/mistralai"},
    {"name":"Mixtral 8x22B","highlight":"Open MoE","hf_url":"https://huggingface.co/mistralai"}
  ]'::jsonb,
  false,
  'Feb 2026'
),
(
  'phi',
  'Phi',
  'Microsoft',
  'Microsoft''s Phi family: small, capable open-weight models optimized for efficiency and edge deployments.',
  'Φ',
  'from-green-500 to-emerald-600',
  null,
  null,
  'Free',
  'Fast',
  'Transformer',
  true,
  true,
  null,
  array['Edge and on-device', 'Low-cost inference', 'Good for constrained deployments'],
  array['Not best for frontier reasoning', 'Requires careful prompting/tuning for complex tasks'],
  array['Small models','Edge','Open source','Coding'],
  array['Use quantized variants for device deployment', 'Constrain tool use in agents', 'Add domain RAG for factual apps'],
  'https://huggingface.co/microsoft',
  'https://huggingface.co/microsoft',
  'https://huggingface.co/microsoft',
  'MIT / Microsoft license (varies)',
  '[
    {"name":"Phi-4","highlight":"Small but strong","hf_url":"https://huggingface.co/microsoft"},
    {"name":"Phi-3.5","highlight":"Edge-ready","hf_url":"https://huggingface.co/microsoft"}
  ]'::jsonb,
  false,
  'Feb 2026'
),
(
  'grok',
  'Grok',
  'xAI',
  'xAI''s Grok family: models tuned for real-time information access and tool use; lineup includes both proprietary and open releases.',
  '⚡',
  'from-slate-500 to-zinc-700',
  null,
  null,
  'API',
  'Fast',
  'Transformer',
  false,
  true,
  null,
  array['Real-time oriented assistants', 'Tool use', 'Strong general chat experiences'],
  array['Vendor lock-in', 'Release cadence is fast', 'Open/closed licensing varies by version'],
  array['Chatbots','Agents','Multimodal','Enterprise'],
  array['Verify licensing per release', 'Track safety behavior changes', 'Use evals for upgrades'],
  'https://docs.x.ai',
  'https://x.ai',
  'https://huggingface.co/xai-org',
  'Proprietary / xAI license (varies)',
  '[
    {"name":"Grok 3","highlight":"Latest flagship"},
    {"name":"Grok 2.5 (open)","highlight":"Open release","hf_url":"https://huggingface.co/xai-org"}
  ]'::jsonb,
  true,
  'Feb 2026'
)
on conflict (slug) do update set
  name = excluded.name,
  company = excluded.company,
  description = excluded.description,
  logo = excluded.logo,
  color = excluded.color,
  parameters = excluded.parameters,
  context_window = excluded.context_window,
  pricing = excluded.pricing,
  speed = excluded.speed,
  architecture = excluded.architecture,
  is_open_source = excluded.is_open_source,
  is_multimodal = excluded.is_multimodal,
  benchmarks = excluded.benchmarks,
  strengths = excluded.strengths,
  weaknesses = excluded.weaknesses,
  use_cases = excluded.use_cases,
  considerations = excluded.considerations,
  api_docs_url = excluded.api_docs_url,
  homepage_url = excluded.homepage_url,
  huggingface_url = excluded.huggingface_url,
  license = excluded.license,
  versions = excluded.versions,
  is_trending = excluded.is_trending,
  release_date = excluded.release_date,
  updated_at = now();

